Repository LawsonCheng/poke, pull requests merged in 2021-07, with the labels that each got.

#27 Develop
  README.md
  lib/helpers/Event.d.ts
  lib/helpers/Event.js
  lib/index.js
  lib/interfaces/PokeOption.d.ts
  lib/interfaces/PokeReturn.d.ts
  package.json
  src/helpers/Event.ts
  src/index.ts
  src/interfaces/PokeOption.ts
  src/interfaces/PokeReturn.ts
  tests/gzip.js
  tests/gzip.test.js
Labels: enhancement

#48 Better types
  lib/helpers/Event.d.ts
  lib/helpers/Event.js
  lib/helpers/JSON.d.ts
  lib/helpers/JSON.js
  lib/index.d.ts
  lib/index.js
  lib/interfaces/PokeOption.d.ts
  lib/interfaces/PokeResult.d.ts
  lib/interfaces/PokeResult.js
  lib/interfaces/PokeReturn.d.ts
  lib/interfaces/Protocol.d.ts
  lib/interfaces/Protocol.js
  src/helpers/Event.ts
  src/helpers/JSON.ts
  src/index.ts
  src/interfaces/PokeOption.ts
  src/interfaces/PokeResult.ts
  src/interfaces/PokeReturn.ts
  src/interfaces/Protocol.ts
Labels: enhancement, good first issue

#53 Develop
  src/index.ts
Labels: bug
